version: '1'

services:
  app:
    image: 'sbwebapi:latest'
    build:
      context: .
    container_name: sbwebapi-app
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - db
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sbwebapidb
      - SPRING_DATASOURCE_USERNAME=sbwebapidb
      - SPRING_DATASOURCE_PASSWORD=sbwebapidb

  db:
    image: 'postgres:14.6-alpine'
    container_name: sbwebapi-db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=sbwebapidb
      - POSTGRES_PASSWORD=sbwebapidb
